### ISSUE TITLE
Add instructions to release on PyPI and conda forge

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/extension-cookiecutter-ts#101]
At the moment the `3.0` branch of the cookiecutter mentions how to install the extension, but doesn't say how to release to PyPI and conda-forge:

https://github.com/jupyterlab/extension-cookiecutter-ts/tree/d8c08687f8661545a65d65ab8eb9433267a45b35/%7B%7Bcookiecutter.python_name%7D%7D

We should a section with the following commands:

```
python setup.py sdist bdist_wheel
twine upload dist/*
```

**Comment by jtpio** [comment]
The widget cookiecutter has some instructions here:

https://github.com/jupyter-widgets/widget-ts-cookiecutter#releasing-your-initial-packages

**Comment by goanpeca** [comment]
How about automating the release process on GH CI, so that the tag triggers the whole process and publishes things using a PyPI token, hopefully associated to the bot account.

Thoughts?

**Comment by jtpio** [comment]
Sounds good!

Maybe this could be made as an opt-in (or opt-out) option while going through the steps of the cookiecutter?

**Comment by jtpio** [comment]
I've used the "GitHub Release" event before to trigger automated releases to PyPI and npm, but doing it on a tag could also work.

**Comment by goanpeca** [comment]
Cool, I will take a look at ti :-)

**Comment by jtpio** [comment]
Awesome, thanks!

**Comment by chrisjsewell** [comment]
Yeh added to this, it would be good to have some minimal instructions for uploading to npm (so it can be found by the Extension Manager), and a CI setup 👍 
As a "Python first" developer; PyPI and Conda I know well, but I've never released to npm before 😬 I imagine I won't be the only one with this kind of user profile.

**Comment by jtpio** [comment]
> so it can be found by the Extension Manager

Yes, and also so it can be used by other extensions or alternative distributions if needed :+1: 

Usually for `npm` a single `npm publish` is enough (and an initial `npm login` to authenticate)

**Comment by chrisjsewell** [comment]
Thanks, that what I had hoped!
I assume the `package.json` section:

```
  "jupyterlab": {
    "discovery": {
      "server": {
        "managers": [
          "pip"
        ],
        "base": {
          "name": "jlab_aiidatree"
        }
      }
    },
```

is all I need to have the manager aware of the server side requirement
