### ISSUE TITLE
Ways to ensure python and node versions remain coherent

### ISSUE THREAD

**Issue by echarles** [jupyterlab/extension-cookiecutter-ts#102]
It would be logical to have the version pulled from the `package.json` rather than from `_version.py`

The generated artifact is a python package, but having two places to define the version is not how it should be.

This has been implemented by @jtpio in https://github.com/jtpio/jupyterlab-python-file/pull/19

**Comment by jtpio** [comment]
Some widget authors also do this to keep the Python and JS versions in sync.

**Comment by goanpeca** [comment]
Are we using already bump2version? That has made my life easy with many projects.

**Comment by echarles** [comment]
bump2version is used in the jupyerlab release scripts. I don't think it is used in `jupyterlab.upgrade_extension`.

I guess the idea of the cookiecutter is to enforce specific versions based on the branches user requests, so we don't need to bump versions here - e.g. `cookiecutter  https://github.com/jupyterlab/extension-cookiecutter-ts --checkout 3.0` will enforce deps version for jlab3

**Comment by goanpeca** [comment]
>I guess the idea of the cookiecutter is to enforce specific versions based on the branches user requests, so we don't need to bump versions here - e.g. cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts --checkout 3.0 will enforce deps version for jlab3

You are right

**Comment by jtpio** [comment]
Fixed by #108
