### ISSUE TITLE
Make the 3.0 branch the default branch?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/extension-cookiecutter-ts#136]
This was briefly discussed in https://github.com/jupyterlab/jupyterlab/pull/9630

And would be similar to what the `jupyterlab_apod` repo does: https://github.com/jupyterlab/jupyterlab_apod

Since the JupyterLab upgrade script checks out the `3.0` branch of this cookiecutter to perform the upgrade:

https://github.com/jupyterlab/jupyterlab/blob/58d4f6de6eb8544c88e9580b9b1b35416f0c0173/jupyterlab/upgrade_extension.py#L16

Having `3.0` as default would make it possible to iterate on the cookiecutter without having to backport each change to a separate branch.

cc @fcollonval

**Comment by jasongrout** [comment]
> Having `3.0` as default would make it possible to iterate on the cookiecutter without having to backport each change to a separate branch.

+1

**Comment by jtpio** [comment]
@jasongrout are you able to to make `3.0` the default branch?

Maybe the simplest could be to delete the existing `3.0` branch, and then use the GitHub branch rename feature in the repo settings?

**Comment by blink1073** [comment]
I updated the default branch to be 3.0

**Comment by jtpio** [comment]
Thanks!
