### ISSUE TITLE
Add "author_name" in package.json and setup.py

### ISSUE THREAD

**Issue by janjagusch** [jupyterlab/extension-cookiecutter-ts#139]
I receive the following warning during the package build:

```sh
$ python setup.py sdist bdist_wheel
# output truncated for visibility ...
warning: check: missing meta-data: if 'author' supplied, 'author_email' should be supplied too
```

I could get rid of that warning by adding "author_name" to the `package.json` and referencing it in `setup.py`.

I'd be glad to open a PR on this, if that's something you want to have fixed. :)

**Comment by blink1073** [comment]
> I'd be glad to open a PR on this, if that's something you want to have fixed. :)

Yes, please!

**Comment by janjagusch** [comment]
> > I'd be glad to open a PR on this, if that's something you want to have fixed. :)
> 
> Yes, please!

Cool, will do that today. I assume we will have to make the same change in https://github.com/jupyterlab/extension-cookiecutter-js, right? And also I believe the tutorial would need to be slightly adjusted (https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html). Should I create follow up issues, @blink1073?

**Comment by blink1073** [comment]
> Should I create follow up issues, @blink1073?

Yes, please do.  Thank you for your help!
