### ISSUE TITLE
Installation will not work if assets are not found and jupyter-packaging is not installed

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/extension-cookiecutter-ts#159]
If JavaScript build assets are not there and if jupyter-packaging is not installed, the installation will be broken without any error message. This is due to the following try-except:

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/3.0/%7B%7Bcookiecutter.python_name%7D%7D/setup.py#L72-L84

**Comment by krassowski** [comment]
Just came here to note the same after seeing https://discourse.jupyter.org/t/extension-migration-issue-from-jupyterlab-2-x-to-3-x/9871. The current implementation requires `jupyter_packaging` to be a runtime dependency, which should not be the case I think?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/extension-migration-issue-from-jupyterlab-2-x-to-3-x/9871/2
