### ISSUE TITLE
Can't initialize cookiecutter or clone the git repo on Windows

### ISSUE THREAD

**Issue by dmedv** [jupyterlab/extension-cookiecutter-ts#160]
## Description

The repository contains a path that is invalid on Windows.

## Reproduce

1. Run `cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts`
2. See error `Command '['git', 'clone', 'https://github.com/jupyterlab/extension-cookiecutter-ts']' returned non-zero exit status 128.`
3. Run `git clone https://github.com/jupyterlab/extension-cookiecutter-ts`
4. See error `invalid path '{{cookiecutter.python_name}}/jupyter-config/nb-config/{{cookiecutter.python_name | replace('-', '_')}}.json'`

## Context

- Operating System and version: Windows 10
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for reporting the issue @dmedv 

> To fix the problem a good solution would be to use hidden template variable prefixed with `__`:

https://github.com/cookiecutter/cookiecutter/blob/52dd18513bbab7f0fbfcb2938c9644d9092247cf/cookiecutter/prompt.py#L187

**Comment by fcollonval** [comment]
Actually the `__` feature is not available on the stable version :disappointed:
