### ISSUE TITLE
master vs 3.0 branch

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/extension-cookiecutter-ts#186]
It looks like the master and 3.0 branches have diverged quite a bit at this point, with the 3.0 branch being the main repo branch and the most recently updated.

They diverged at the 3.0 tag. Master looks like it has these PRs merged in beyond the 3.0 tag:

* #123
* #124 
* #126 
* #127 
* #128 
* #114 
* #129 
* #130 
* #132 
* #115 
* #134 
* #131 
* #138 

Since the main repo branch is 3.0, I think it makes sense to essentially merge master in (or backport from master) and get rid of the master branch.

**Comment by blink1073** [comment]
> I think it makes sense to essentially merge master in (or backport from master) and get rid of the master branch.

Agreed

**Comment by fcollonval** [comment]
The mentionned PRs where merged in 3.0 in https://github.com/jupyterlab/extension-cookiecutter-ts/pull/133

To check I carry out a merge of master in 3.0 and I can confirm that nothing needs to be changed on 3.0.

The only action left is to remove the `master` branch.

**Comment by blink1073** [comment]
> The only action left is to remove the master branch.

I am doing that now

**Comment by blink1073** [comment]
Done, and I added branch protection to our versioned branches

**Comment by jasongrout** [comment]
Thanks!
