### ISSUE TITLE
`fetchVersion` only works if the extension was built

### ISSUE THREAD

**Issue by loichuder** [jupyterlab/extension-cookiecutter-ts#188]
## Description

This is rather a request for confirmation than a bug report. 

In `_version.py`, `fetchVersion` searches `package.json` in the current folder (that is the folder of the python sources):

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/3.0/%7B%7Bcookiecutter.python_name%7D%7D/%7B%7Bcookiecutter.python_name%7D%7D/_version.py#L7

This means the version resolution works only if the extension was built (i.e. there is a `labextension` folder containing the `package.json` in the current folder). 

Is this the desired behaviour ? Would it not be more robust to search directly for `package.json` in the extension folder (i.e. the parent folder of the python sources) ?

**Comment by fcollonval** [comment]
> This means the version resolution works only if the extension was built

Yes indeed.

> Is this the desired behaviour ? Would it not be more robust to search directly for `package.json` in the extension folder (i.e. the parent folder of the python sources) ?

Unfortunately, we can not look outside of the python package as that code may not be in the source folder.

**Comment by loichuder** [comment]
> Unfortunately, we can not look outside of the python package as that code may not be in the source folder.

Ah indeed, I understand now. Thanks for the clarification !
