### ISSUE TITLE
CookieCutter was working a week ago, broken now

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/extension-cookiecutter-ts#216]
Cookiecutter ran successfully as of a week ago but now seems borked (I had a previously working version but foolishly said "yes" to download it again!;-):

- missing requirement: `jupyter_packaging`

In addition, several files appear to be missing, such as:
- `src/index.ts`
- `tsconfig.json`

From https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html#create-an-extension-project, where it says _"Change to the directory the cookiecutter created and list the files.You should see a list like the following"_, I don't:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/82988/162939018-53c8fc10-65c0-47fa-ae8c-2ee991139693.png">

**Comment by martinRenou** [comment]
> missing requirement: jupyter_packaging

The jupyter_packaging build dependency is still here: https://github.com/jupyterlab/extension-cookiecutter-ts/blob/3.0/%7B%7Bcookiecutter.python_name%7D%7D/pyproject.toml#L2

Do you see it missing somewhere else?

> In addition, several files appear to be missing, such as:
src/index.ts
tsconfig.json

I just generated a project from the 3.0 branch and those files are not missing.

From your screenshot, I see a `lib` directory which only appears if you built the extension (and I suspect you couldn't build the extension with a missing `tsconfig.json`). So are you sure the directory you're showing the content off is the one that the cookiecutter generated?

**Comment by psychemedia** [comment]
Clean run:

```
cookiecutter https://github.com/jupyterlab/extension-cookiecutter-js -f
You've downloaded /Users/tonyhirst/.cookiecutters/extension-cookiecutter-js before. Is it okay to delete and re-download it? [yes]: 
author_name []: a   
author_email []: a
python_name [myextension]: cookiecutter-test-delme
labextension_name [cookiecutter-test-delme]: 
project_short_description [A JupyterLab extension.]: 
has_binder [n]: 
repository [https://github.com/github_username/cookiecutter-test-delme]: 
```

Then:

```
ls -R cookiecutter-test-delme/

LICENSE			cookiecutter-test-delme	pyproject.toml
MANIFEST.in		install.json		setup.py
README.md		lib			style
binder			package.json

cookiecutter-test-delme//binder:
environment.yml	postBuild

cookiecutter-test-delme//cookiecutter-test-delme:
__init__.py	_version.py

cookiecutter-test-delme//lib:
index.js

cookiecutter-test-delme//style:
base.css	index.css	index.js
```

**Comment by psychemedia** [comment]
I also note the `has_binder [n]` default and I still get the `binder/` directory?

**Comment by psychemedia** [comment]
DOh! -js in the cookiecutter call...

**Comment by martinRenou** [comment]
You are using extension-cookiecutter-**js**, not extension-cookiecutter-**ts**
