### ISSUE TITLE
Check release test fails for a fresh cookiecutter due to `ui-tests` path issues

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/extension-cookiecutter-ts#221]
## Description

Freshly seeded extension from cookiecutter will fail `check_release` test because of incorrect relative paths to `ui-tests` scripts in `/ui-tests/README.md` and outdated link to https://playwright.dev/docs/intro/ (now https://playwright.dev/docs/intro - no trailing slash):

```
FAILED ui-tests/README.md::/home/runner/work/myextension/myextension/.jupyter_releaser_checkout/ui-tests/README.md <a href=https://playwright.dev/docs/intro/>
FAILED ui-tests/README.md::/home/runner/work/myextension/myextension/.jupyter_releaser_checkout/ui-tests/README.md <a href=../playwright.config.js>
FAILED ui-tests/README.md::/home/runner/work/myextension/myextension/.jupyter_releaser_checkout/ui-tests/README.md <a href=../jupyter_server_test_config.py>
```

The bigger problem is that we are not testing the tests.

## Reproduce

1. Cut cookies with all settings default but enabled tests
2. Push to GitHub
3. Check release fails

## Expected behavior

Tests pass.

## Context

3.0 branch

**Comment by fcollonval** [comment]
Closing as fixed by #224 - thanks
