### ISSUE TITLE
 I don't know which part is wrong

### ISSUE THREAD

**Issue by Shaiken** [jupyterlab/extension-cookiecutter-ts#227]
i just create a new extension project, but not very smooth.

input command  "jlpm install" fail or "jupyter labextension install" fail

that my env.

nvm ls
```
        v15.0.1
->     v16.17.0
default -> 15.0.1 (-> v15.0.1)
node -> stable (-> v16.17.0) (default)
stable -> 16.17 (-> v16.17.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/gallium (-> v16.17.0)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.20.0 (-> N/A)
lts/gallium -> v16.17.0
```

jupyter --v
```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 3.2.9
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat         : 5.0.8
traitlets        : 4.3.3
```

ubuntu nvidia container 
```
NVIDIA Release 20.11-tf1 (build 17379723)
TensorFlow Version 1.15.4
```

i do this .
step1.  change jupyter lab version, "pip install jupyterlab==3.2.9"
step2. change node version, "nvm use v16.17.0"
step3. check out 3.0 version, cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts --checkout v3.0, only this version jlpm install will be fine, but could not labextension install success package.

![image](https://user-images.githubusercontent.com/30071132/186097157-e9175611-37c9-4ca4-a7da-5d1d45245ba3.png)

i just want empty page work good, a new icon page github source.
![image](https://user-images.githubusercontent.com/30071132/186090435-bb57080f-2a62-4dc7-87bb-5a6f983f427f.png)

**Comment by Shaiken** [comment]
i copy a index.js to /usr/local/share/jupyter/lab/staging/node_modules/GISAIv3/style
It seems to work.

**Comment by fcollonval** [comment]
@Shaiken It seems you are mixing different ways to deal with an extension.

Starting with JupyterLab v3, it is recommended to use pre-built extension and not source extension any longer (this is the expectation of the cookiecutter).

When you get your extension skeleton from the cookiecutter template, you should execute the following command in the extension folder:

```
# Install package in development mode
pip install -e .
# Link your development version of the extension with JupyterLab
jupyter labextension develop . --overwrite
```

I highly recommend not using `jupyter labextension install` any longer.

**Comment by Shaiken** [comment]
@fcollonval thank you!! i got it.
