### ISSUE TITLE
Unused `MANIFEST.in` after hatchling migration?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/extension-cookiecutter-ts#237]
If I understand correctly, `MANIFEST.in` has no effect for sdist in when using hatchling (source: https://scikit-hep.org/developer/pep621). I was a bit confused as to why files I excluded in manifest were still in the `dist/*tar.gz`. I think that we should drop manifest.

Also, it would be great if we could document these kind of changes in a changelog as it seems like playing an endless catch up game on packaging with these subtle changes.

**Comment by krassowski** [comment]
Though manifest seemed like a better idea, as we could exclude `binder` but still track changes with VCS. The equivalent in hatch is `[tool.hatch.build.targets.sdist]`. We already use it to exclude `.github` but not `binder`, `lib`, `**/node_modules` as we do for manfest.

**Comment by fcollonval** [comment]
Fixed by #238
