### ISSUE TITLE
Referenced release workflow was removed

### ISSUE THREAD

**Issue by keckelt** [jupyterlab/extension-cookiecutter-ts#285]
## Description

Hi,
in RELEASE.md, the _typical workflow_  section of [jupyter_releaser](https://github.dev/jupyter-server/jupyter_releaser) is referenced, but that section [was removed](https://github.com/jupyter-server/jupyter_releaser/commit/0f3098b7282e9d441ed9b15a52cfd02220f3f40d).

Should it point to the [How-to Guides](https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/index.html)?

---

Maybe an additional remark: I don't fully understand the  [Convert a Repo to Use Releaser from Releaser](https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/convert_repo_from_releaser.html) and [Convert a Repo to Use Releaser from Repo](https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/convert_repo_from_repo.html) headlines. Reading the steps, is the 

1. option using an additional repo (a fork of releaser) that has all the tokens of GitHub, PyPI and npm, and the 
2. option providing these settings in the extension repository and using the "official"/unforked jupyter-releaser?

**Comment by fcollonval** [comment]
Thanks @keckelt 

There is two ways of using the releaser:

- (historic one) you fork the jupyter_releaser and execute actions to release package from that fork to carry release; this is what I'm using to release Lumino and JupyterLab for example - see [my fork action](https://github.com/fcollonval/jupyter_releaser/actions/workflows/draft-changelog.yml)
- (new recommended one) you set GitHub actions directly in the package; this is what is configured for [jupyter-server](https://github.com/jupyter-server/jupyter_server/actions/workflows/prep-release.yml) for example.

Would you be willing to update the template to use the new recommended way?

**Comment by keckelt** [comment]
Thanks for the clarification @fcollonval! I'll prepare a PR.

**Comment by fcollonval** [comment]
Closed by #295
