### ISSUE TITLE
I tried to use it in a directory without permissions, and I it crashed and don't give the correct error

### ISSUE THREAD

**Issue by marian-vignau** [jupyterlab/extension-cookiecutter-ts#45]
I installed cookie cutter using conda, following https://jupyterlab.readthedocs.io/en/stable/developer/xkcd_extension_tutorial.html#xkcd-extension-tutorial
I stay in the conda software directory, ~/miniconda.
When I run this cookie cutter extension, crashes saying
>>> FileNotFoundError: [Errno 2] No such file or directory: '/home/marian/miniconda3/myxkcd/.gitignore'

The correct answer must be PermissionsError, because this was the real original error, normal user  doesn't have write privileges.

**Comment by jasongrout** [comment]
Can you tell us exactly what commands you ran and which command gave you the error? The question is here is whether this should be reported to conda or the cookiecutter project.

**Comment by fcollonval** [comment]
Closing this as inactive.
