### ISSUE TITLE
Strict null checks should default to true

### ISSUE THREAD

**Issue by afshin** [jupyterlab/extension-cookiecutter-ts#71]
As a time-saving quality of life measure for any extension author who might want their extension merged into core, or just wants more reliable code, I propose we turn this check on. This default was a bit painful when we were merging `@jupyterlab/debugger` into core.

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/cb9ca8c37bf1c5c28be61b31e6fcd0cf60487a5f/%7B%7Bcookiecutter.extension_name%7D%7D/tsconfig.json#L19

**Comment by bollwyvl** [comment]
It's probably worth exploring whatever other goodies are available in ts 3.9+... there's really no reason to do a new-start without the maximum support from the compiler.

I do usually end up having to add `skipLibCheck: true`, as a lot of the stuff out there is pretty crazy and not so well-behaved.

**Comment by vidartf** [comment]
> I do usually end up having to add skipLibCheck: true, as a lot of the stuff out there is pretty crazy and not so well-behaved.

It is also a little quicker :)
