### ISSUE TITLE
Update scripts to build with source maps by default

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/extension-cookiecutter-ts#96]
At the moment on the `3.0` branch, `jlpm run build` will run the following:

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/479bb3d0a7f6c57ee1bf8d37e94c9bc1758e6c3c/%7B%7Bcookiecutter.python_name%7D%7D/package.json#L28-L31

However extension authors will want to use the browser dev tools to debug the extension, which requires running `jlpm run build:labextension:dev` to generate the source maps:

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/479bb3d0a7f6c57ee1bf8d37e94c9bc1758e6c3c/%7B%7Bcookiecutter.python_name%7D%7D/package.json#L30

Maybe we could make that command the default for `jlpm run build` and add a new `build:prod` to be used by the `prepare` script?

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/479bb3d0a7f6c57ee1bf8d37e94c9bc1758e6c3c/%7B%7Bcookiecutter.python_name%7D%7D/package.json#L39

(follow-up to https://github.com/jupyterlab/jupyterlab/pull/8961)

**Comment by jtpio** [comment]
> and add a new `build:prod`

Or actually rename `build:dev` to `build:prod` and make `build` be the dev script.

**Comment by hbcarlos** [comment]
I think developing an extension we will use more times the `build:dev`.  Would be nice to have `build` as a default for `build:dev`.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/extension-cookiecutter-ts/pull/98
